### ISSUE TITLE
0.0.9 ChatGPT-Next-Web 仍然返回 Failed to fetch

### ISSUE THREAD

**Issue by bailob** [Ink-Osier/PandoraToV1Api#3]
docker 后台log：
```
[2023-12-15 06:59:56.195901] New Request
api_key: ***
model: gpt-4-mobile
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
38.*** - - [15/Dec/2023:06:59:58 +0000] "POST /v1/chat/completions HTTP/1.1" 200 0 "http://***:3000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[2023-12-15 06:59:58 +0000] [9] [ERROR] Error handling request /v1/chat/completions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 339, in handle_request
    for item in respiter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/app/main.py", line 381, in generate
    message_status = message.get("status")
AttributeError: 'NoneType' object has no attribute 'get'
38.*** - - [15/Dec/2023:06:59:58 +0000] "POST /v1/chat/completions HTTP/1.1" 500 0 "-" "-"
```

**Comment by Ink-Osier** [comment]
这个问题经常出现么

**Comment by bailob** [comment]
我这是第一次部署，没有成功联通过，我的PandoraNext是正常运行的

**Comment by Ink-Osier** [comment]
可以试试更新到最新版再看看日志显示什么

**Comment by YANGHAI666** [comment]
我也是这个问题

**Comment by Ink-Osier** [comment]
你们是不是都是在别人的网页上用的，如果你的next web是https协议的网站，你在网页端选择“自定义接口”填入http的本项目链接的话是会被浏览器的跨域安全策略拦截的

**Comment by Ink-Osier** [comment]
可以看一下f12控制台报错，应该会有报错详细原因

**Comment by Ink-Osier** [comment]
如果是https的原因建议反向代理后再在网页填入使用

**Comment by bailob** [comment]
更新到了0.1.2，pandora、本项目、next web都反代走https了，还是提示跨域访问问题

f12显示：
```
Access to fetch at 'https://***/v1/chat/completions' from origin 'https://***' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

docker log:
```
[2023-12-16 10:04:07.666293] New Request
api_key: fk-***
model: gpt-4-mobile
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
message 为空: data_json: {'message': None, 'conversation_id': '87d0bc72-***', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}
172.18.*** - - [16/Dec/2023:10:04:08 +0000] "POST /v1/chat/completions HTTP/1.1" 200 0 "https://***/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
[2023-12-16 10:04:08 +0000] [9] [ERROR] Error handling request /v1/chat/completions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 339, in handle_request
    for item in respiter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/app/main.py", line 417, in generate
    message_status = message.get("status")
AttributeError: 'NoneType' object has no attribute 'get'
172.18.*** - - [16/Dec/2023:10:04:08 +0000] "POST /v1/chat/completions HTTP/1.1" 500 0 "-" "-"
```

**Comment by Ink-Osier** [comment]
你这个容器的报错检查一下pandora的auto_conv_arkose:true是否设置正确以及pandora是否升级到了最新版本

**Comment by bailob** [comment]
> 你这个容器的报错检查一下pandora的auto_conv_arkose:true是否设置正确以及pandora是否升级到了最新版本

正常了，感谢感谢
