### ISSUE TITLE
无法使用gpt-4-s或mobile

### ISSUE THREAD

**Issue by cyx1322** [Ink-Osier/PandoraToV1Api#9]
在Pandoranext都正常；
但在[PandoraToV1Api](https://github.com/Ink-Osier/PandoraToV1Api)中，gpt-3.5-turbo可正常使用，而无法使用gpt-4。

日志
api_key: fk-xxxxxxxxxxxxx
model: gpt-4-mobile
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
content_type: text
last_content_type: None
message 为空: data_json: {'message': None, 'conversation_id': 'xxxxxxxxxxxxx', 'error': 'Our systems have detected unusual activity from your system. Please try again later.'}
172.20.0.5 - - [16/Dec/2023:07:22:11 +0000] "POST /v1/chat/completions HTTP/1.1" 200 0 "-" "Go-http-client/1.1"
[2023-12-16 07:22:11 +0000] [11] [ERROR] Error handling request /v1/chat/completions
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 282, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/gthread.py", line 339, in handle_request
    for item in respiter:
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
    return self._next()
  File "/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/app/main.py", line 417, in generate
    message_status = message.get("status")
AttributeError: 'NoneType' object has no attribute 'get'
172.20.0.5 - - [16/Dec/2023:07:22:11 +0000] "POST /v1/chat/completions HTTP/1.1" 500 0 "-" "-"

**Comment by Ink-Osier** [comment]
auto_conv_arkose:true开启了么

**Comment by cyx1322** [comment]
开启了

**Comment by cyx1322** [comment]
刚才想了想，更新了一下pandoranext，就又可以用了，有类似问题的朋友可以参考一下。

**Comment by Ink-Osier** [comment]
👍🏻
